# Generated by Django 4.2.2 on 2024-08-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_ethereum_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ethereum_balance',
            field=models.IntegerField(default=0),
        ),
    ]
