# Generated by Django 4.2.2 on 2024-08-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_ethereum_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ethereum_balance',
            field=models.FloatField(default=0.0),
        ),
    ]
