# Generated by Django 4.2.2 on 2024-08-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_ethereum_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ethereum_address',
            field=models.CharField(default='Default_Ehtereum_Address', max_length=256, unique=True),
        ),
    ]
